# Generated by Django 2.2.3 on 2020-11-01 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DigestRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt', models.DateTimeField(verbose_name='Date&time')),
                ('title', models.CharField(max_length=256, unique=True, verbose_name='Title')),
                ('url', models.CharField(max_length=256, unique=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Digest Record',
                'verbose_name_plural': 'Digest Records',
            },
        ),
    ]
