# Generated by Django 2.2.3 on 2020-11-05 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gatherer', '0004_add_digest_record_gather_dt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='digestrecord',
            name='gather_dt',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Gather Date&time'),
        ),
    ]
