# Generated by Django 2.2.3 on 2020-11-15 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gatherer', '0005_change_digest_record_gather_dt_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='digestrecord',
            name='subcategory',
            field=models.CharField(blank=True, choices=[('EVENTS', 'events'), ('INTROS', 'intros'), ('OPENING', 'opening'), ('NEWS', 'news'), ('DIY', 'diy'), ('LAW', 'law'), ('KnD', 'knd'), ('SYSTEM', 'system'), ('SPECIAL', 'special'), ('DATABASES', 'db'), ('MULTIMEDIA', 'multimedia'), ('SECURITY', 'security'), ('DEVOPS', 'devops'), ('DATA_SCIENCE', 'data_science'), ('WEB', 'web'), ('DEV', 'dev'), ('HISTORY', 'history'), ('MANAGEMENT', 'management'), ('USER', 'user'), ('GAMES', 'games'), ('HARDWARE', 'hardware'), ('MISC', 'misc')], max_length=256, null=True, verbose_name='Subcategory'),
        ),
    ]
