# Generated by Django 2.2.3 on 2021-01-16 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gatherer', '0009_add_digest_record_subcategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='digestrecord',
            name='dt',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date&time'),
        ),
    ]
