# Generated by Django 2.2.3 on 2021-01-16 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gatherer', '0010_allow_digestrecord_dt_to_be_null'),
    ]

    operations = [
        migrations.AlterField(
            model_name='digestrecord',
            name='title',
            field=models.CharField(max_length=256, verbose_name='Title'),
        ),
    ]
