# Generated by Django 2.2.13 on 2021-04-14 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gatherer', '0012_digestrecord_keywords'),
    ]

    operations = [
        migrations.CreateModel(
            name='DigestRecordDuplicate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('digest_records', models.ManyToManyField(related_name='duplicates', to='gatherer.DigestRecord', verbose_name='Digest Record')),
            ],
        ),
    ]
