# Generated by Django 2.2.13 on 2021-04-16 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gatherer', '0013_digestrecordduplicate'),
    ]

    operations = [
        migrations.AddField(
            model_name='digestrecordduplicate',
            name='digest_number',
            field=models.IntegerField(blank=True, null=True, verbose_name='Digest Number'),
        ),
    ]
