# Generated by Django 2.2.13 on 2021-06-17 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gatherer', '0014_digestrecordduplicate_digest_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='digestrecord',
            name='subcategory',
            field=models.CharField(blank=True, choices=[('EVENTS', 'events'), ('INTROS', 'intros'), ('OPENING', 'opening'), ('NEWS', 'news'), ('DIY', 'diy'), ('LAW', 'law'), ('KnD', 'knd'), ('SYSTEM', 'system'), ('SPECIAL', 'special'), ('EDUCATION', 'education'), ('DATABASES', 'db'), ('MULTIMEDIA', 'multimedia'), ('MOBILE', 'mobile'), ('SECURITY', 'security'), ('SYSADM', 'sysadm'), ('DEVOPS', 'devops'), ('DATA_SCIENCE', 'data_science'), ('WEB', 'web'), ('DEV', 'dev'), ('HISTORY', 'history'), ('MANAGEMENT', 'management'), ('USER', 'user'), ('GAMES', 'games'), ('HARDWARE', 'hardware'), ('MISC', 'misc')], max_length=256, null=True, verbose_name='Subcategory'),
        ),
    ]
