# Generated by Django 2.2.13 on 2021-07-04 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gatherer', '0016_new_category_testing'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
            },
        ),
        migrations.AddField(
            model_name='digestrecord',
            name='projects',
            field=models.ManyToManyField(related_name='records', to='gatherer.Project', verbose_name='Projects'),
        ),
    ]
