# Generated by Django 2.2.13 on 2021-07-12 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gatherer', '0018_fill_projects'),
    ]

    operations = [
        migrations.AlterField(
            model_name='digestrecord',
            name='projects',
            field=models.ManyToManyField(blank=True, null=True, related_name='records', to='gatherer.Project', verbose_name='Projects'),
        ),
    ]
