# Generated by Django 2.2.13 on 2021-07-14 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gatherer', '0020_digestrecord_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='digestrecord',
            name='state',
            field=models.CharField(blank=True, choices=[('UNKNOWN', 'unknown'), ('IN_DIGEST', 'in_digest'), ('OUTDATED', 'outdated'), ('IGNORED', 'ignored'), ('FILTERED', 'filtered')], max_length=256, null=True, verbose_name='State'),
        ),
    ]
