# Generated by Django 2.2.13 on 2021-07-14 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gatherer', '0021_added_filtered_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='digestrecord',
            name='projects',
            field=models.ManyToManyField(blank=True, related_name='records', to='gatherer.Project', verbose_name='Projects'),
        ),
    ]
