# Generated by Django 2.2.13 on 2021-07-14 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gatherer', '0023_fill_empty_projects_as_fn_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='digestrecord',
            name='category',
            field=models.CharField(blank=True, choices=[('UNKNOWN', 'unknown'), ('NEWS', 'news'), ('ARTICLES', 'articles'), ('RELEASES', 'releases'), ('OTHER', 'other')], max_length=15, null=True, verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='digestrecord',
            name='language',
            field=models.CharField(blank=True, choices=[('ENGLISH', 'eng'), ('RUSSIAN', 'rus')], max_length=15, null=True, verbose_name='Language'),
        ),
        migrations.AlterField(
            model_name='digestrecord',
            name='state',
            field=models.CharField(blank=True, choices=[('UNKNOWN', 'unknown'), ('IN_DIGEST', 'in_digest'), ('OUTDATED', 'outdated'), ('IGNORED', 'ignored'), ('FILTERED', 'filtered')], max_length=15, null=True, verbose_name='State'),
        ),
        migrations.AlterField(
            model_name='digestrecord',
            name='subcategory',
            field=models.CharField(blank=True, choices=[('EVENTS', 'events'), ('INTROS', 'intros'), ('OPENING', 'opening'), ('NEWS', 'news'), ('DIY', 'diy'), ('LAW', 'law'), ('KnD', 'knd'), ('SYSTEM', 'system'), ('SPECIAL', 'special'), ('EDUCATION', 'education'), ('DATABASES', 'db'), ('MULTIMEDIA', 'multimedia'), ('MOBILE', 'mobile'), ('SECURITY', 'security'), ('SYSADM', 'sysadm'), ('DEVOPS', 'devops'), ('DATA_SCIENCE', 'data_science'), ('WEB', 'web'), ('DEV', 'dev'), ('TESTING', 'testing'), ('HISTORY', 'history'), ('MANAGEMENT', 'management'), ('USER', 'user'), ('GAMES', 'games'), ('HARDWARE', 'hardware'), ('MISC', 'misc')], max_length=15, null=True, verbose_name='Subcategory'),
        ),
    ]
