# Generated by Django 2.2.13 on 2021-07-14 04:03

from django.db import migrations
from gatherer.models import DigestRecordSubcategory


def migrate_system_to_sysadm_subcategory(apps, schema_editor):
    dr_model = apps.get_model('gatherer', 'DigestRecord')
    for dr in dr_model.objects.all():
        if dr.subcategory == DigestRecordSubcategory.SYSTEM.name:
            dr.subcategory = DigestRecordSubcategory.SYSADM.name
            dr.save()


class Migration(migrations.Migration):

    dependencies = [
        ('gatherer', '0026_set_more_correct_org_subcategory_value'),
    ]

    operations = [
        migrations.RunPython(migrate_system_to_sysadm_subcategory, migrations.RunPython.noop),
    ]
