# Generated by Django 2.2.13 on 2021-07-14 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gatherer', '0027_migrate_system_subcategory_to_sysadm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='digestrecord',
            name='category',
            field=models.CharField(blank=True, choices=[('UNKNOWN', 'unknown'), ('NEWS', 'news'), ('ARTICLES', 'articles'), ('VIDEOS', 'videos'), ('RELEASES', 'releases'), ('OTHER', 'other')], max_length=15, null=True, verbose_name='Category'),
        ),
    ]
