# Generated by Django 2.2.13 on 2021-07-23 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gatherer', '0030_keyword'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(max_length=64, verbose_name='Name'),
        ),
    ]
