# Generated by Django 2.2.13 on 2021-08-15 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gatherer', '0032_fill_keywords'),
    ]

    operations = [
        migrations.AddField(
            model_name='digestrecord',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
    ]
