# Generated by Django 2.2.13 on 2021-07-14 04:03

import os
import json

from django.db import migrations, models
from gatherer.models import DigestRecordsSource


def fill_sources(apps, schema_editor):
    sources_path = os.path.join(os.path.dirname(os.path.realpath(__file__)),
                                'data',
                                'digestrecordssources.json')
    with open(sources_path, 'r') as fin:
        sources = json.load(fin)

    for source_name, source_enabled in sources:
        source = DigestRecordsSource(name=source_name, enabled=source_enabled)
        source.save()


class Migration(migrations.Migration):

    dependencies = [
        ('gatherer', '0035_create_digestrecordssource'),
    ]

    operations = [
        migrations.RunPython(fill_sources, migrations.RunPython.noop),
    ]
