# Generated by Django 2.2.13 on 2021-07-14 04:03

import os
import json

from django.db import migrations, models
from gatherer.models import DigestRecordsSource


def add_youtube_channels(apps, schema_editor):
    youtube_sources_names = [
        'PlafonAtYouTube',
        'TheLinuxExperimentAtYouTube',
        'NikolayIvanovichAtYouTube',
        'SwitchedToLinuxAtYouTube',
        'LearnLinuxTVAtYouTube',
        'DmitryRobionekAtYouTube',
    ]
    for source_name in youtube_sources_names:
        source = DigestRecordsSource(name=source_name, enabled=True)
        source.save()


class Migration(migrations.Migration):

    dependencies = [
        ('gatherer', '0037_add_missed_meta_description_to_digestrecordssource'),
    ]

    operations = [
        migrations.RunPython(add_youtube_channels, migrations.RunPython.noop),
    ]
