# Generated by Django 2.2.13 on 2021-08-22 04:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gatherer', '0038_add_youtube_channels_sources'),
    ]

    operations = [
        migrations.AddField(
            model_name='digestrecord',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='gatherer.DigestRecordsSource'),
        ),
    ]
