# Generated by Django 2.2.13 on 2021-08-22 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gatherer', '0039_add_digestrecord_source'),
    ]

    operations = [
        migrations.CreateModel(
            name='DigestIssue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(unique=True, verbose_name='Номер дайджеста')),
                ('habr_url', models.CharField(max_length=128, unique=True, verbose_name='Ссылка на Хабр')),
            ],
            options={
                'verbose_name': 'Выпуск дайджеста',
                'verbose_name_plural': 'Выпуски дайджеста',
            },
        ),
    ]
