# Generated by Django 2.2.13 on 2021-08-22 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gatherer', '0041_fill_digest_issues'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='digestissue',
            options={'verbose_name': 'Digest Issue', 'verbose_name_plural': 'Digest Issues'},
        ),
    ]
