# Generated by Django 2.2.13 on 2021-08-22 11:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gatherer', '0043_fix_descriptions_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='digestrecord',
            name='digest_issue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='gatherer.DigestIssue'),
        ),
    ]
