# Generated by Django 2.2.13 on 2021-07-14 04:03

import os
import json

from django.db import migrations, models
from gatherer.models import DigestIssue, DigestRecord


def connect_issues(apps, schema_editor):
    for digest_record in DigestRecord.objects.all():
        if not digest_record.digest_number:
            continue
        digest_issue = DigestIssue.objects.get(number=digest_record.digest_number)
        digest_record.digest_issue = digest_issue
        digest_record.save()


class Migration(migrations.Migration):

    dependencies = [
        ('gatherer', '0044_add_digestrecord_digest_issue'),
    ]

    operations = [
        migrations.RunPython(connect_issues, migrations.RunPython.noop),
    ]
