# Generated by Django 2.2.13 on 2021-07-14 04:03
import logging
import os
import json

from django.db import migrations, models
from gatherer.models import Keyword


def fill_lf_keywords(apps, schema_editor):
    sources_path = os.path.join(os.path.dirname(os.path.realpath(__file__)),
                                'data',
                                'lfkeywords.json')
    with open(sources_path, 'r') as fin:
        keywords_names = json.load(fin)

    for keyword_name in keywords_names:
        keyword = Keyword(name=keyword_name)
        keyword.save()


class Migration(migrations.Migration):

    dependencies = [
        ('gatherer', '0046_add_digestrecord_title_keywords'),
    ]

    operations = [
        migrations.RunPython(fill_lf_keywords, migrations.RunPython.noop),
    ]
