# Generated by Django 2.2.13 on 2021-08-22 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gatherer', '0049_set_digest_issue_url_not_required'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='keyword',
            unique_together={('name', 'category')},
        ),
    ]
