# Generated by Django 2.2.13 on 2021-08-23 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gatherer', '0050_set_unique_together_for_keyword_name_and_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='digestrecordduplicate',
            name='digest_issue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='gatherer.DigestIssue', verbose_name='Digest Issue'),
        ),
    ]
