# Generated by Django 2.2.13 on 2021-09-11 11:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gatherer', '0053_add_osm_source'),
    ]

    operations = [
        migrations.CreateModel(
            name='DigestGatheringIteration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt', models.DateTimeField(verbose_name='Date&time')),
                ('count', models.IntegerField(verbose_name='Gathered Records Count')),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='gatherer.DigestRecordsSource')),
            ],
            options={
                'verbose_name': 'Digest Gathering Iteration',
                'verbose_name_plural': 'Digest Gathering Iterations',
            },
        ),
    ]
