# Generated by Django 2.2.13 on 2021-09-12 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gatherer', '0056_rename_digestgatheringiteration_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='digestgatheringiteration',
            name='saved_count',
            field=models.IntegerField(blank=True, null=True, verbose_name='Saved Records Count'),
        ),
    ]
