# Generated by Django 2.2.13 on 2021-09-13 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gatherer', '0058_add_messengers_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='digestrecordssource',
            name='data_url',
            field=models.CharField(blank=True, max_length=512, null=True, unique=True, verbose_name='Data URL'),
        ),
        migrations.AddField(
            model_name='digestrecordssource',
            name='language',
            field=models.CharField(blank=True, choices=[('ENGLISH', 'eng'), ('RUSSIAN', 'rus')], max_length=15, null=True, verbose_name='Language'),
        ),
        migrations.AddField(
            model_name='digestrecordssource',
            name='projects',
            field=models.ManyToManyField(blank=True, null=True, related_name='sources', to='gatherer.Project', verbose_name='Projects'),
        ),
    ]
