# Generated by Django 2.2.13 on 2021-09-14 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gatherer', '0060_fill_sources_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='digestgatheringiteration',
            name='overall_count',
            field=models.IntegerField(blank=True, null=True, verbose_name='Overall Records Count'),
        ),
    ]
