# Generated by Django 2.2.13 on 2021-09-16 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gatherer', '0061_digestgatheringiteration_overall_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='digestissue',
            name='is_special',
            field=models.BooleanField(blank=True, null=True, verbose_name='Is Special'),
        ),
    ]
