# Generated by Django 2.2.13 on 2021-07-14 04:03

from django.db import migrations
from gatherer.models import (
    DigestIssue,
)


def fill_is_special(apps, schema_editor):
    issues = DigestIssue.objects.all()
    for issue in issues:
        if issue.number in (50, 63, 87):
            issue.is_special = True
        else:
            issue.is_special = False
        issue.save()


class Migration(migrations.Migration):

    dependencies = [
        ('gatherer', '0062_digestissue_is_special'),
    ]

    operations = [
        migrations.RunPython(fill_is_special, migrations.RunPython.noop),
    ]
