# Generated by Django 2.2.13 on 2021-07-14 04:03

from django.db import migrations
from gatherer.models import (
    DigestRecordsSource,
    Project,
    Language,
)


def add_unix_way_source(apps, schema_editor):
    foss_news_project = Project.objects.get(name='FOSS News')
    unix_way_source = DigestRecordsSource(name='UnixWayAtYouTube',
                                          enabled=True,
                                          data_url='https://www.youtube.com/feeds/videos.xml?channel_id=UCgY050JAKtaew3IEgGW1qSQ',
                                          language=Language.RUSSIAN.name)
    unix_way_source.save()
    unix_way_source.projects.set([foss_news_project])
    unix_way_source.save()


class Migration(migrations.Migration):

    dependencies = [
        ('gatherer', '0063_set_digestissue_is_special'),
    ]

    operations = [
        migrations.RunPython(add_unix_way_source, migrations.RunPython.noop),
    ]
