# Generated by Django 2.2.24 on 2021-09-27 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gatherer', '0064_add_unix_way_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='keyword',
            name='enabled',
            field=models.BooleanField(default=True, verbose_name='Is enabled'),
        ),
    ]
