# Generated by Django 2.2.24 on 2021-10-19 02:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gatherer', '0069_duplicate_state'),
    ]

    operations = [
        migrations.RenameField(
            model_name='digestrecord',
            old_name='category',
            new_name='content_type',
        ),
    ]
