# Generated by Django 2.2.24 on 2021-10-19 03:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gatherer', '0073_fix_content_category_verbose_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='keyword',
            old_name='category',
            new_name='content_category',
        ),
        migrations.AlterUniqueTogether(
            name='keyword',
            unique_together={('name', 'content_category')},
        ),
    ]
