# Generated by Django 2.2.24 on 2021-10-23 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gatherer', '0075_fix_keyword_content_type_verbose_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='keyword',
            name='proprietary',
            field=models.BooleanField(default=False, verbose_name='Is proprietary'),
        ),
    ]
