# Generated by Django 2.2.24 on 2021-10-24 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gatherer', '0076_keyword_proprietary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='digestrecordssource',
            name='projects',
            field=models.ManyToManyField(blank=True, related_name='sources', to='gatherer.Project', verbose_name='Projects'),
        ),
    ]
