# Generated by Django 2.2.24 on 2021-10-24 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gatherer', '0077_removed_useless_null_parameter'),
    ]

    operations = [
        migrations.AddField(
            model_name='digestrecord',
            name='cleared_description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
    ]
