# Generated by Django 2.2.24 on 2021-11-06 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gatherer', '0082_remove_jenkins_duplicate'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DigestRecordDuplicate',
            new_name='SimilarDigestRecords',
        ),
    ]
