# Generated by Django 2.2.24 on 2021-11-06 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gatherer', '0083_rename_digestrecordduplicate_to_similardigestrecords'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='similardigestrecords',
            options={'verbose_name': 'Similar Digest Records', 'verbose_name_plural': 'Similar Digest Records'},
        ),
        migrations.AlterField(
            model_name='similardigestrecords',
            name='digest_records',
            field=models.ManyToManyField(related_name='similar_records', to='gatherer.DigestRecord', verbose_name='Digest Record'),
        ),
    ]
