# Generated by Django 2.2.24 on 2021-11-12 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gatherer', '0086_remove_obsolete_digest_number_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='digestrecord',
            name='is_main',
            field=models.BooleanField(blank=True, default=None, null=True, verbose_name='Is main post'),
        ),
    ]
