# Generated by Django 2.2.24 on 2021-12-18 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gatherer', '0087_added_none_default_value_for_record_is_main_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='digestrecord',
            name='text',
            field=models.TextField(blank=True, null=True, verbose_name='Text'),
        ),
    ]
