# Generated by Django 2.2.24 on 2021-12-18 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gatherer', '0088_digestrecord_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='digestrecordssource',
            name='text_fetching_enabled',
            field=models.BooleanField(default=False, verbose_name='Text fetching enabled'),
        ),
    ]
