# Generated by Django 2.2.3 on 2020-12-03 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gatherer', '0007_new_subcategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='digestrecord',
            name='state',
            field=models.CharField(blank=True, choices=[('UNKNOWN', 'unknown'), ('IN_DIGEST', 'in_digest'), ('OUTDATED', 'outdated'), ('IGNORED', 'ignored')], max_length=256, null=True, verbose_name='State'),
        ),
    ]
