# Generated by Django 2.2.13 on 2021-08-21 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tbot', '0003_set_tid_unique'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='telegrambotdigestrecordcategorizationattempt',
            options={'verbose_name': 'Telegram Bot Digest Record Categorization Attempt', 'verbose_name_plural': 'Telegram Bot Digest Record Categorization Attempts'},
        ),
        migrations.AlterModelOptions(
            name='telegrambotuser',
            options={'verbose_name': 'Telegram Bot User', 'verbose_name_plural': 'Telegram Bot Users'},
        ),
    ]
