# Generated by Django 2.2.13 on 2021-08-28 09:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tbot', '0004_add_missed_tbot_models_meta_descriptions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegrambotdigestrecordcategorizationattempt',
            name='digest_record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tbot_estimations', to='gatherer.DigestRecord', verbose_name='Digest Record under Categorization'),
        ),
    ]
