# Generated by Django 2.2.24 on 2021-09-27 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tbot', '0006_add_messengers_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramBotUserGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Name')),
                ('users', models.ManyToManyField(related_name='groups', to='tbot.TelegramBotUser')),
            ],
            options={
                'verbose_name': 'Telegram Bot User Group',
                'verbose_name_plural': 'Telegram Bot Users Groups',
            },
        ),
    ]
