# Generated by Django 2.2.24 on 2021-09-27 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tbot', '0008_fill_users_groups'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegrambotdigestrecordcategorizationattempt',
            name='estimated_state',
            field=models.CharField(blank=True, choices=[('UNKNOWN', 'unknown'), ('IN_DIGEST', 'in_digest'), ('OUTDATED', 'outdated'), ('IGNORED', 'ignored'), ('FILTERED', 'filtered'), ('SKIPPED', 'skipped')], max_length=15, null=True, verbose_name='Estimated State'),
        ),
    ]
