# Generated by Django 2.2.24 on 2021-09-27 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tbot', '0009_added_skipped_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegrambotusergroup',
            name='name',
            field=models.CharField(max_length=256, unique=True, verbose_name='Name'),
        ),
    ]
