# Generated by Django 2.2.24 on 2021-10-19 03:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tbot', '0011_duplicate_state'),
    ]

    operations = [
        migrations.RenameField(
            model_name='telegrambotdigestrecordcategorizationattempt',
            old_name='estimated_category',
            new_name='estimated_content_type',
        ),
    ]
