# Generated by Django 2.2.24 on 2021-10-19 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tbot', '0012_rename_estimated_category_to_estimated_content_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegrambotdigestrecordcategorizationattempt',
            name='estimated_content_type',
            field=models.CharField(blank=True, choices=[('UNKNOWN', 'unknown'), ('NEWS', 'news'), ('ARTICLES', 'articles'), ('VIDEOS', 'videos'), ('RELEASES', 'releases'), ('OTHER', 'other')], max_length=15, null=True, verbose_name='Estimated Content Type'),
        ),
    ]
