# Generated by Django 2.2.24 on 2021-10-19 03:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tbot', '0013_fix_estimated_content_type_verbose_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='telegrambotdigestrecordcategorizationattempt',
            old_name='estimated_subcategory',
            new_name='estimated_content_category',
        ),
    ]
