# Generated by Django 2.2.24 on 2021-10-24 02:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gatherer', '0080_fixed_cleared_description_verbose_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lemma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=256, verbose_name='Text')),
            ],
        ),
        migrations.CreateModel(
            name='DigestRecordLemma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('digest_record', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gatherer.DigestRecord')),
                ('lemma', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ds.Lemma')),
            ],
        ),
    ]
