# Generated by Django 2.2.24 on 2021-10-24 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gatherer', '0080_fixed_cleared_description_verbose_name'),
        ('ds', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lemma',
            name='text',
            field=models.CharField(max_length=256, unique=True, verbose_name='Text'),
        ),
        migrations.AlterUniqueTogether(
            name='digestrecordlemma',
            unique_together={('digest_record', 'lemma')},
        ),
    ]
