# Generated by Django 2.2.24 on 2021-10-24 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ds', '0002_set_unique'),
    ]

    operations = [
        migrations.AddField(
            model_name='digestrecordlemma',
            name='count',
            field=models.IntegerField(default=0, verbose_name='Count'),
        ),
    ]
