# Generated by Django 2.2.24 on 2021-10-24 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ds', '0003_digestrecordlemma_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lemma',
            name='text',
            field=models.CharField(max_length=2048, unique=True, verbose_name='Text'),
        ),
    ]
