name: FNGS Develop Deploy

on:
  push:
    branches:
      - develop

concurrency:
  group: deploy_develop
  cancel-in-progress: false

jobs:
  deploy_develop:
    runs-on: self-hosted
    if: github.repository == 'foss-news/foss-news-gathering-server'
    env:
      FNGS_DEV_DIR: /home/gim6626/fngs-dev
    steps:
    - name: Checkout "develop" branch
      working-directory: ${{ env.FNGS_DEV_DIR }}
      run: git checkout develop
    - name: Fetch code
      working-directory: ${{ env.FNGS_DEV_DIR }}
      run: git pull
    - name: Install requirements
      working-directory: ${{ env.FNGS_DEV_DIR }}
      run: |
        source env/bin/activate
        pip3 install -r requirements.txt
    - name: Stop FNGS Dev
      run: sudo systemctl stop fngs-dev.service
    - name: Run migrations
      working-directory: ${{ env.FNGS_DEV_DIR }}
      run: |
        source env/bin/activate
        cd fngs
        python3 manage.py migrate
    - name: Start FNGS Dev
      run: sudo systemctl start fngs-dev.service
    - name: Wait a bit to let FNGS Dev start
      run: sleep 5
    - name: Check FNGS Dev status
      run: systemctl status fngs-dev.service
