name: FNGS Develop Deploy

on:
  push:
    branches:
      - develop

jobs:
  deploy_develop:
    runs-on: self-hosted
    env:
      FNGS_DEV_DIR: /home/gim6626/fngs-dev
    steps:
    - name: Checkout "develop" branch
      working-directory: $FNGS_DEV_DIR
      run: git checkout develop
    - name: Fetch code
      working-directory: $FNGS_DEV_DIR
      run: git pull
    - name: Install requirements
      working-directory: $FNGS_DEV_DIR
      run: |
        source env/bin/activate
        pip3 install -r requirements.txt
    - name: Run migrations
      working-directory: $FNGS_DEV_DIR
      run: |
        source env/bin/activate
        cd fngs
        python3 manage.py migrate
    - name: Restart FNGS Dev
      run: sudo systemctl restart fngs-dev.service
    - name: Wait a bit to let FNGS Dev start
      run: sleep 5
    - name: Check FNGS Dev status
      run: systemctl status fngs-dev.service
