name: FNGS Develop Deploy

on:
  push:
    branches:
      - develop

jobs:
  deploy_develop:
    runs-on: self-hosted
    steps:
    - name: Checkout "develop" branch
      working-directory: /home/gim6626/fngs-dev
      run: git checkout develop
    - name: Fetch code
      working-directory: /home/gim6626/fngs-dev
      run: git pull
    - name: Switch to virtual environment
      working-directory: /home/gim6626/fngs-dev
      run: source env/bin/activate
    - name: Install requirements
      working-directory: /home/gim6626/fngs-dev
      run: pip3 install -r requirements.txt
    - name: Run migrations
      working-directory: /home/gim6626/fngs-dev/fngs
      run: python3 manage.py migrate
    - name: Restart FNGS Dev
      run: sudo systemctl restart fngs-dev.service
    - name: Wait a bit to let FNGS Dev start
      run: sleep 5
    - name: Check FNGS Dev status
      run: systemctl status fngs-dev.service
